# Registry client configuration
eureka:
  instance:
    healthCheckUrlPath: /production-support/health
    statusPageUrlPath: /production-support/health
  client:
    serviceUrl:
      defaultZone: http://registry-editorial:8761/registry/eureka/

authentication:
  jms:
    topic:
      login: VirtualTopic.Backbase.auth.login
      logout: VirtualTopic.Backbase.auth.logout

auth:
  token:
    converter:
      validationEnabled: true
      allowedApiKeys: A3HC6A0347HH,7HHGI3ZYLL6R

token:
  converter:
    allowedApiHeader: X-TokenConverter-ApiKey

# Configure Internal JWT
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY
# Configure External JWT
    external:
      signature:
        key:
          type: ENV
          value: EXTERNAL_SIG_SECRET_KEY
      encryption:
        key:
          type: ENV
          value: EXTERNAL_ENC_SECRET_KEY

#Define app defaults
endpoints:
  jmx:
    domain: ${spring.application.name}

# Disable healthcheck for JMS
# Service health should be UP even if JMS broker is not available.
management:
  health:
    jms:
      enabled: false